### ISSUE TITLE
Implement course availability calendar

### ISSUE THREAD

**Issue by otarza** [Antishcool/antischool-d8#12]
გვჭირდება მექანიზმი რომლის საშუალებითაც კურსს დავუმატებთ შესაძლო გაკვეთილების დროებს და თარიღებს. სხვა სიტყვებით რომ ვთქვათ თითოეულ კურსს უნდა ჰქონდეს თავისი კალენდარი. 

ამ დავალების შესასრულებელი ზუსტი გზა ჯერ არ ვიცით. ამიტომ უნდა გამოვიკვლიოთ არსებული მოდულები და იარაღები. 

დავიწყოთ ამ მოდულით: https://www.drupal.org/project/calendar_systems
- დააინსტალირე და გაერკვიე როგორ მუშაობს;
- გაარკვიე რამდენად გამოგვადგება დავალების შესასრულებლად;
- თუ გამოგვადგება განვიხილოთ და შესაბამისი გეგმაც დავსახოთ.

**Comment by zboh** [comment]
რა ვარიანტებიც ვნახე, ეს სოლუშენი ყველაზე შესაბამისი მომეჩვენა
იქნებ შეხედოთ - https://www.drupal.org/project/bee 
+ები
1. შესაძლებელია როგორც დღიური, ასევე საათობრივი availability
2. ნებისმიერი node შეიძლება გახდეს bookable
3. შესაძლებელია იქვე გადახდის მიბმაც.
