### ISSUE TITLE
Implement Reviews per course

### ISSUE THREAD

**Issue by otarza** [Antishcool/antischool-d8#13]
#11 უნდა დაიმერჯოს სანამ ამ დავალებას დავიწყებთ რადგან კურსის კონტენტის ტიპი მანდ იქმნება.

კურსებისთვის გვჭირდება Review - ების და Rating - ების მექანიზმი.

იმისთვის რომ ამ ორივე ფუნქციონალის კომბინაცია შევძლოთ სავარაუდოდ დაგვჭირდება Comments მოდულის (რომელიც core - ის ნაწილი და დაყენება არ სჭირდება) და rate მოდულის (https://www.drupal.org/project/rate) ერთად გამოყენება. 

უფრო კონკრეტულად ასე წარმომიდგენია:
- უნდა შეიქმნას ახალი კომენტარის ტიპი comment type - რომელსაც ერქმევა Review
- ამ კომენტარის ტიპს უნდა ჰქონდეს რეიტინგის ფუნქციონალი rate მოდულის გამოყენებით
- ეს კომენტარის ტიპი უნდა მიებას Course - ის კონტენტის ტიპზე. 

ეს არის სავარაუდო გეგმა, გამოსაკვლევია იმუშავებს თუ არა.

**Comment by zura12337** [comment]
მე როგორც მივხვდი, კომენტარის ტიპს არ უნდა მიებას rate მოდული. პირდაპირ კურსის ტიპს უნდა დაემატოს rate field და ეგრე მოხდება კურსის შეფასება.
